### ISSUE TITLE
TFTP Timeout

### ISSUE THREAD

**Issue by slaecker** [linuxserver/docker-netbootxyz#17]
The TFTP download times out. This can be reproduced in Kubernetes and Podman. The reason seems to be that only the initial connection is done through UDP port 69 but the transfer is done via a random port set during connection, see [Wikipedia](https://en.wikipedia.org/wiki/Trivial_File_Transfer_Protocol#Details).

To use TFTP through docker we have therefor two options:

1. Run in host network which seems a bit over the top and conflicts already mapped host ports on my side (80 and 3000). An option would be to make the config web interface and nginx.
1. Set a fixed port for the TFTP connection on server side that can be forwarded to the container.

------------------------------

## Expected Behavior
TFTP download works

## Current Behavior
TFTP download times out

## Steps to Reproduce
1. Run the image (see command provided below)
2. Test TFTP download
```
curl -o netboot.xyz.kpxe tftp://localhost/netboot.xyz.kpxe -vvv
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying ::1:69...
* Connected to localhost () port 69 (#0)
* set timeouts for state 0; Total 300, retry 6 maxtry 50
  0     0    0     0    0     0      0      0 --:--:--  0:04:59 --:--:--     0* TFTP response timeout
  0     0    0     0    0     0      0      0 --:--:--  0:05:00 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:05:00 --:--:--     0
* Closing connection 0
curl: (28) TFTP response timeout
```
3. Downloading from inside the Docker (or Kubernetes) network works fine

## Environment
**OS: Arch Linux / Raspbian Buster**      
**CPU architecture:** x86_64 / arm64      
**How docker service was installed:**      
Tested on a K3S cluster on Raspbian Buster and my local Arch Linux with podman

## Command used to create docker container (run/create/compose/screenshot)
```
docker run \
  --name=netbootxyz-test \
  -e PUID=1000 \
  -e PGID=1000 \
  -p 3000:3000 \
  -p 69:69/udp \
  -p 8088:80 \
  linuxserver/netbootxyz
```

## Docker logs
```
Trying to pull docker.io/linuxserver/netbootxyz...
Getting image source signatures
Copying blob f64e86613f22 done  
Copying blob 28e749efc215 done  
Copying blob 7de41abee0a4 done  
Copying blob 6eb1af1a521f done  
Copying blob 66fa287bda10 done  
Copying config 2df7c84587 done  
Writing manifest to image destination
Storing signatures
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
netboot.xyz: https://opencollective.com/netbootxyz/donate

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-nginx-config: executing... 
[cont-init.d] 20-nginx-config: exited 0.
[cont-init.d] 36-download-menus: executing... 
[netbootxyz-init] Downloading Netboot.xyz at 2.0.17
cp: -r not specified; omitting directory '/config/menus/remote/sigs'
[cont-init.d] 36-download-menus: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
listening on *:3000
```

**Comment by aptalca** [comment]
tftp connection and transfer are both done through port 69, not a random port. It works just fine with bridge networking.

You're curling localhost, which is using ipv6 `Trying ::1:69...`, which may be the issue. Or other firewall or networking related issue.

**Comment by thelamer** [comment]
Do not run tests from the same host, they don't work through loopback for some reason. If you hit 69 from another host it will work.

**Comment by vangorra** [comment]
I posted a workaround for this issue in #11

**Comment by robsel-0** [comment]
My solution to get netboot.xyz to work with rootless podman in bridged network is this: `TFTPD_OPTS=--tftp-single-port`
This option forces TFTP to use only port 69 within the container.

I use iptables to forward host port 69 to the container.


compose.yml:
```
services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    container_name: netbootxyz
    environment:
      - MENU_VERSION=2.0.84 # optional
      - NGINX_PORT=80 # optional
      - WEB_APP_PORT=3000 # optional
      - TFTPD_OPTS=--tftp-single-port
    volumes:
      - ../data/netboot.xyz/config:/config # optional
      - ../data/netboot.xyz/assets:/assets # optional
    ports:
      - 3100:3000  # optional, destination should match ${WEB_APP_PORT} variable above.
      - 6969:69/udp
      - 8083:80  # optional, destination should match ${NGINX_PORT} variable above.
    restart: unless-stopped

```
