### ISSUE TITLE
Tftp Not working in K8s

### ISSUE THREAD

**Issue by MGlants** [linuxserver/docker-netbootxyz#22]
## Expected Behavior
TFTP connection works fine

## Current Behavior
Tftp connection timed out 
## Steps to Reproduce
1. Install in K8s cluster
2. Try to reach tftp server from outside

## Environment
**Ubuntu 18.10**
**CPU architecture:** x86_64**
K8s TKG

## Command used to create docker container (run/create/compose/screenshot)
```apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbootxyz-deployment
  labels:
    app: netbootxyz
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: netbootxyz
  template:
    metadata:
      labels:
        name: netbootxyz
    spec:
      containers:
        - name: netbootxyz
          image: "linuxserver/netbootxyz:tftp"
          imagePullPolicy: IfNotPresent
          ports:
            - name: webconfig
              containerPort: 3000
              protocol: TCP
            - name: tftp
              containerPort: 69
              protocol: UDP
            - name: webassets
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: netbootxyz-config
      volumes:
      - name: netbootxyz-config
        persistentVolumeClaim:
          claimName: netbootxyz-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: netbootxyz-tcp-svc
  labels:
    app: netbootxyz
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    protocol: TCP
    name: webconfig
    targetPort: webconfig
  - port: 80
    protocol: TCP
    name: webassets
    targetPort: webassets
  selector:
    name: netbootxyz
---
apiVersion: v1
kind: Service
metadata:
  name: netbootxyz-udp-svc
  labels:
    app: netbootxyz
spec:
  type: LoadBalancer
  ports:
  - port: 69
    protocol: UDP
    name: tftp
    targetPort: tftp
  selector:
    name: netbootxyz
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbootxyz-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

```
## Docker logs
Everything is fine

##Maybe this will help
#https://github.com/projectcalico/calico/issues/3578

**Comment by Tokugero** [comment]
Firstly: These specs aren't officially supported outside of single host deployments such as with Docker-Compose or just regular Docker, you may find better support for these types of debug sessions in our official discord, where a few of our community members are as stubborn as you and I: https://discord.gg/KxzYczed


That being said:
tftp works fine for me in k8s with the netboot image for baremetal & proxmox at least:

```
spec:
  externalTrafficPolicy: Local
  ports:
  - name: tftp
    nodePort: 32694
    port: 69
    protocol: UDP
    targetPort: 69
  selector:
    run: netbootxyz
  sessionAffinity: None
  type: LoadBalancer
  ```
  
  These are my running specs, I'm using MetalLB to expose this with Calico as my CNI.
  
  It's worth noting that there is still an outstanding configuration in my environment where Hyper-V is waiting on a port to be open from the pod IP rather than what is being advertised since netboot is technically bound to a different network and being nat'd through to MetalLB.
  
 If you want to keep debugging here, can you explain more about what you're trying to boot and any steps you used to troubleshoot so far?

**Comment by tibbon** [comment]
I'm running into this as well. I'm using MetalLB and k3s

```
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: network
  labels:
    server: netbootxyz
  name: netbootxyz
spec:
  replicas: 1
  selector:
    matchLabels:
      server: netbootxyz
  template:
    metadata:
      labels:
        server: netbootxyz
    spec:
      containers:
        - name: netbootxyz
          resources:
            limits:
              memory: 200M
              cpu: 10m
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          image: linuxserver/netbootxyz:arm64v8-latest
          imagePullPolicy: Always
          stdin: true
          tty: true
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/arch: arm64
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: netbootxyz
    kubernetes.io/name: CoreDNS
  name: netbootxyz-tcp
  namespace: network
spec:
  ports:
  - name: connect
    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    k8s-app: netbootxyz
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: netbootxyz
    kubernetes.io/name: CoreDNS
  name: netbootxyz-udp
  namespace: network
spec:
  externalTrafficPolicy: Local
  ports:
  - name: tftp
    nodePort: 32694
    port: 69
    protocol: UDP
    targetPort: 69
  selector:
    run: netbootxyz
  sessionAffinity: None
  type: LoadBalancer
```

```
# kubectl get services --all-namespaces
network        netbootxyz-tcp              LoadBalancer   10.43.75.138    192.168.1.206   3000:31476/TCP,8080:30979/TCP              39s
network        netbootxyz-udp              LoadBalancer   10.43.4.9       192.168.1.204   69:32694/UDP                               3s
```

```
tftp 192.168.1.204
tftp> status
Connected to 192.168.1.204.
Mode: netascii Verbose: off Tracing: off
Rexmt-interval: 5 seconds, Max-timeout: 25 seconds
tftp> get netboot.xyz.efi
Transfer timed out.

tftp>
```
