### ISSUE TITLE
Editing boot.cfg and other TFTP files has no effect

### ISSUE THREAD

**Issue by dchidell** [linuxserver/docker-netbootxyz#23]
## Expected Behavior
Editing files via the UI (on port 3000) should change the behaviour in line with the edits made.

## Current Behavior
If a file is edited via the UI (even something simple, like a change to the title in boot.cfg) this change is not reflected when the PXE server is booted from. These files seem to be constantly pulled from the ONLINE netboot.xyz repository, this means than no customisation can be performed when using this image in the way of adding your own menus or boot options.

I have confirmed that changes made in the UI does indeed change the files within /config/menus and confirmed that the TFTP server is indeed listening within this directory - it simply is not serving these files locally, and is rather always pulling files from online. I can only assume this has something to do with the precompiled binary kpxe file which is included.

I have no logs from the tftp server to show which files are actually being accessed or not via TFTP. 

## Steps to Reproduce

1. Deploy a container using the below docker-compose file:
2. Connect to port 3000 to access the UI
3. Edit boot.cfg to contain some minor trivial change
4. Ensure DHCP server is providing the correct bootfile name and IP 
5. PXE boot a machine
6. Observe that the changes to boot.cfg are not reflected

## Environment
**OS:** Debian 9
**CPU architecture:** x86_64
**How docker service was installed:**

Standard docker installation, following the instructions for Debian.

## Command used to create docker container (run/create/compose/screenshot)

```

version: '2'
services:

  netbootxyz:
    image: linuxserver/netbootxyz
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      # - MENU_VERSION=1.9.9
    volumes:
      - /mnt/docker/netbootxyz_config/config:/config
      - /mnt/docker/netbootxyz_config/assets:/assets 
    ports:
      - 3000:3000
      - 69:69/udp
      - 8181:80
```

## Docker logs

There's nothing here of relevance.
