### ISSUE TITLE
container won't start start after update from 0.6.4-ls44 to 0.6.4-ls45

### ISSUE THREAD

**Issue by hugalafutro** [linuxserver/docker-netbootxyz#32]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
container should start as normal

## Current Behavior
container doesn't start, keeps spamming this error in log (the hex value changes each "tick")
```
netbootxyz    | #
netbootxyz    | # Fatal error in , line 0
netbootxyz    | # unreachable code
netbootxyz    | #
netbootxyz    | #
netbootxyz    | #
netbootxyz    | #FailureMessage Object: 0x7ec3723c
```

## Steps to Reproduce

1. have 0.6.4-ls44 up and running
2. run `docker-compose pull && docker compose up -d`
3. ???
4. observe the error

## Environment
**OS:** raspbian buster fully updated
**CPU architecture:** armv7 (raspberry pi 3b+)
**How docker service was installed:**

docker installed form ofifcial repo

## Command used to create docker container (run/create/compose/screenshot)

```
---
version: "2.1"
services:
  netbootxyz:
    image: linuxserver/netbootxyz
    container_name: netbootxyz
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config:/config
      - ./assets:/assets #optional
    ports:
      - 3000:3000
      - 69:69/udp
      - 8182:80 #optional
    restart: unless-stopped

```

## Docker logs

logs above
