### ISSUE TITLE
tftp service fails to run when IPv6 is disabled on Host

### ISSUE THREAD

**Issue by bamhm182** [linuxserver/docker-netbootxyz#38]
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)](https://linuxserver.io)

IPv6 being disabled on the host causes the tftp service to fail

## Expected Behavior

The tftp service should run, even when IPv6 is not available.

## Current Behavior

When IPv6 is disabled on the host box, the script at /etc/services.d/tftp/run exists with code 71 and does not leave the tftp service in a running state.

## Environment

**OS:** Arch Linux
**CPU architecture:** x86_64

IPv6 is disabled on this box

**How docker service was installed:**

The following docker-compose.yml

```
version: "3.9"
services:
  netbootxyz:
    image: lscr.io/linuxserver/netbootxyz:0.6.6
    container_name: netboot
    environment:
      - PUID=1000
      - PGID=1000
      - PORT_RANGE=30000:30010
      - SUBFOLDER=/
    ports:
      - 69:69/udp
      - 6969:80/tcp
    restart: unless-stopped
    volumes:
      - config:/config
      - assets:/assets

volumes:
  config:
  assets:
```

## Command used to create docker container (run/create/compose/screenshot)
`docker-compose up `

## Docker logs

Nothing to indicate there is a problem.

## Workaround

I have added the environmental variable "IPV4=true" and I have created the file `/config/custom-services.d/tftp` with the following contents:

```
#!/usr/bin/with-contenv bash

exec /usr/sbin/in.tftpd \
        --foreground --listen --user abc --secure ${PORT_RANGE:+--port-range $PORT_RANGE} ${IPV4:+--ipv4} /config/menus
```

The `--ipv4` flag is what is required for /usr/sbin/in.tftpd to not fail.

## Proposed workaround

Adapt the change made in my `custom-services.d` script to the official tftp service script.
