### ISSUE TITLE
Doesn't work at all.

### ISSUE THREAD

**Issue by Smyl3** [linuxserver/docker-netbootxyz#45]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

TFTP service doesn't work at all on Raspberry. (netbootxyz tftp branch)
I used the offical guide about docker compose YAML to create container with portainer.
I tried with docker's host network mode too with the same result.
Docker image "3x3cut0r/tftpd-hpa" tftp server service worked instantly even with bridged network mode with only udp port no. 69 opened. I tried it with the netboot.xyz.efi image downloaded manually.

From client PC with this image:
```
C:\Users\xy>tftp -i 192.168.1.10 get netboot.xyz.efi
 Connect request failed
```

From client PC with  other tftp image:
```
C:\Users\xy>tftp -i 192.168.1.10 get netboot.xyz.efi
Transfer successful: 1078272 bytes in 2 second(s), 539136 bytes/s
```

------------------------------

## Expected Behavior

PXE network boot is working.

## Current Behavior

TFTP server doesnt work.
When I try PXE boot I see that:
```
>Checking media presence...
>MEdia present...
>Start PXE over IPV4.
   Station IP address is 192.168.1.160
   
   Server IP address is 192.168.1.10
   NBP filename is netboot.xyz.efi
   NBP filesize is 0 bytes.
   PXE-E23: Client received TFTP error from server.
```

## Steps to Reproduce

1. create and run container with the offical guide by portainer
2.
3.
4.

## Environment
**OS: Dietpi**
**CPU architecture:** arm32
**How docker service was installed:** by builtin repo

## Command used to create docker container (run/create/compose/screenshot)

```
version: "2.1"
services:
  netbootxyz:
    image: lscr.io/linuxserver/netbootxyz:tftp
    network_mode: host
    container_name: netbootxyz
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/dietpi/docker/netbootxyz/config:/config
    ports:
      - 3000:3000
      - 69:69/udp
    restart: unless-stopped
```

## Docker logs

```
[custom-init] No custom services found, skipping...
[migrations] started
[migrations] no migrations found
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support the app dev(s) visit:
netboot.xyz: https://opencollective.com/netbootxyz/donate
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```
