### ISSUE TITLE
[BUG] Internal TFTP server fails to start after version 0.7.1-ls173

### ISSUE THREAD

**Issue by ndizazzo** [linuxserver/docker-netbootxyz#70]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you start the image with the `:latest` tag, the internal TFTP server does not start.

![Screenshot 2025-01-08 at 9 28 46 PM](https://github.com/user-attachments/assets/3bc1ea77-84a7-45e5-b796-670e2ef2affa)

### Expected Behavior

When you start the image with the `:latest` tag, the internal TFTPserver should start.

### Steps To Reproduce

Follow the recommended setup guide from [TechnoTim](https://www.youtube.com/watch?v=4btW5x_clpg)

### Environment

```markdown
- OS: MacOS (docker compose)
- How docker service was installed: docker compose
```

### CPU architecture

arm64

### Docker creation

```bash
version: '3.8'
services:
  netbootxyz:
    image: lscr.io/linuxserver/netbootxyz:latest
    container_name: netbootxyz
    environment:
      - PUID=1000
      - PGID=1000
      - PORT_RANGE=30000:30010
      - WEB_APP_PORT=3000
      - TZ=America/Toronto
    volumes:
      - ./config:/config
      - ./assets:/assets
    ports:
      - 3000:3000   # Web interface
      - 69:69/udp   # TFTP server
      - 8080:80     # HTTP server (optional)
    restart: unless-stopped


`docker compose up`
```

### Container logs

```bash
netbootxyz  | [migrations] started
netbootxyz  | [migrations] no migrations found
netbootxyz  | ───────────────────────────────────────
netbootxyz  | 
netbootxyz  |       ██╗     ███████╗██╗ ██████╗
netbootxyz  |       ██║     ██╔════╝██║██╔═══██╗
netbootxyz  |       ██║     ███████╗██║██║   ██║
netbootxyz  |       ██║     ╚════██║██║██║   ██║
netbootxyz  |       ███████╗███████║██║╚██████╔╝
netbootxyz  |       ╚══════╝╚══════╝╚═╝ ╚═════╝
netbootxyz  | 
netbootxyz  |    Brought to you by linuxserver.io
netbootxyz  | ───────────────────────────────────────
netbootxyz  | 
netbootxyz  | To support the app dev(s) visit:
netbootxyz  | netboot.xyz: https://opencollective.com/netbootxyz/donate
netbootxyz  | 
netbootxyz  | To support LSIO projects visit:
netbootxyz  | https://www.linuxserver.io/donate/
netbootxyz  | 
netbootxyz  | ───────────────────────────────────────
netbootxyz  | GID/UID
netbootxyz  | ───────────────────────────────────────
netbootxyz  | 
netbootxyz  | User UID:    1000
netbootxyz  | User GID:    1000
netbootxyz  | ───────────────────────────────────────
netbootxyz  | Linuxserver.io version: 0.7.3-ls196
netbootxyz  | Build-date: 2025-01-04T03:03:28+00:00
netbootxyz  | ───────────────────────────────────────
netbootxyz  |     
netbootxyz  | [custom-init] No custom files found, skipping...
netbootxyz  | listening on *:3000
netbootxyz  | Connection to localhost (127.0.0.1) 80 port [tcp/http] succeeded!
netbootxyz  | Connection to localhost (::1) 3000 port [tcp/*] succeeded!
netbootxyz  | Connection to localhost (::1) 69 port [udp/tftp] succeeded!
netbootxyz  | [ls.io-init] done.
netbootxyz  | EpQtuhVzudg_rsCmAAAB connected time=1736393512322
```

**Comment by ndizazzo** [comment]
Reverting to a previous version allows me to start the container:

```
version: '3.8'
services:
  netbootxyz:
    image: lscr.io/linuxserver/netbootxyz:0.7.1-ls173
    container_name: netbootxyz
    environment:
      - PUID=1000
      - PGID=1000
      - PORT_RANGE=30000:30010
      - WEB_APP_PORT=3000
      - TZ=America/Toronto
    volumes:
      - ./config:/config
      - ./assets:/assets
    ports:
      - 3000:3000   # Web interface
      - 69:69/udp   # TFTP server
      - 8080:80     # HTTP server (optional)
    restart: unless-stopped
```

![Screenshot 2025-01-08 at 10 30 00 PM](https://github.com/user-attachments/assets/fb1d61e4-6a7f-48fa-9d97-34c6fb9c3a3f)
